$filename = $env:COMPUTERNAME+'_'+$env:UserName
$path = '\\fserver\Resources\Logs\Administrator\'+ $filename + '.txt' 

$isfile = Test-Path $path 
if($isfile -eq "True") {
	#Если Файл существует ...
	Remove-Item -Path $path
	#... удалить файл.
}
$outFile = $path

$userToFind = $env:username
$administratorsAccount = Get-WmiObject Win32_Group -filter "LocalAccount=True AND SID='S-1-5-32-544'"
$administratorQuery = "GroupComponent = `"Win32_Group.Domain='" + $administratorsAccount.Domain + "',NAME='" + $administratorsAccount.Name + "'`""
$user = Get-WmiObject Win32_GroupUser -filter $administratorQuery | select PartComponent |where {$_ -match $userToFind}
$user=$user.PartComponent.Split("\,")[5].Remove(0,5).Replace('"','')
if ($user -eq $userToFind) 
             {Write-Host "Warning: $user is Administrator"}  Out-File $outFile
# SIG # Begin signature block
# MIIOUAYJKoZIhvcNAQcCoIIOQTCCDj0CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUKv9exgG7fWkX8AjAc3y+5UO9
# kpygggn2MIIEmTCCA4GgAwIBAgIPFojwOSVeY45pFDkH5jMLMA0GCSqGSIb3DQEB
# BQUAMIGVMQswCQYDVQQGEwJVUzELMAkGA1UECBMCVVQxFzAVBgNVBAcTDlNhbHQg
# TGFrZSBDaXR5MR4wHAYDVQQKExVUaGUgVVNFUlRSVVNUIE5ldHdvcmsxITAfBgNV
# BAsTGGh0dHA6Ly93d3cudXNlcnRydXN0LmNvbTEdMBsGA1UEAxMUVVROLVVTRVJG
# aXJzdC1PYmplY3QwHhcNMTUxMjMxMDAwMDAwWhcNMTkwNzA5MTg0MDM2WjCBhDEL
# MAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4GA1UE
# BxMHU2FsZm9yZDEaMBgGA1UEChMRQ09NT0RPIENBIExpbWl0ZWQxKjAoBgNVBAMT
# IUNPTU9ETyBTSEEtMSBUaW1lIFN0YW1waW5nIFNpZ25lcjCCASIwDQYJKoZIhvcN
# AQEBBQADggEPADCCAQoCggEBAOnpPd/XNwjJHjiyUlNCbSLxscQGBGue/YJ0UEN9
# xqC7H075AnEmse9D2IOMSPznD5d6muuc3qajDjscRBh1jnilF2n+SRik4rtcTv6O
# KlR6UPDV9syR55l51955lNeWM/4Og74iv2MWLKPdKBuvPavql9LxvwQQ5z1IRf0f
# aGXBf1mZacAiMQxibqdcZQEhsGPEIhgn7ub80gA9Ry6ouIZWXQTcExclbhzfRA8V
# zbfbpVd2Qm8AaIKZ0uPB3vCLlFdM7AiQIiHOIiuYDELmQpOUmJPv/QbZP7xbm1Q8
# ILHuatZHesWrgOkwmt7xpD9VTQoJNIp1KdJprZcPUL/4ygkCAwEAAaOB9DCB8TAf
# BgNVHSMEGDAWgBTa7WR0FJwUPKvdmam9WyhNizzJ2DAdBgNVHQ4EFgQUjmstM2v0
# M6eTsxOapeAK9xI1aogwDgYDVR0PAQH/BAQDAgbAMAwGA1UdEwEB/wQCMAAwFgYD
# VR0lAQH/BAwwCgYIKwYBBQUHAwgwQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL2Ny
# bC51c2VydHJ1c3QuY29tL1VUTi1VU0VSRmlyc3QtT2JqZWN0LmNybDA1BggrBgEF
# BQcBAQQpMCcwJQYIKwYBBQUHMAGGGWh0dHA6Ly9vY3NwLnVzZXJ0cnVzdC5jb20w
# DQYJKoZIhvcNAQEFBQADggEBALozJEBAjHzbWJ+zYJiy9cAx/usfblD2CuDk5oGt
# Joei3/2z2vRz8wD7KRuJGxU+22tSkyvErDmB1zxnV5o5NuAoCJrjOU+biQl/e8Vh
# f1mJMiUKaq4aPvCiJ6i2w7iH9xYESEE9XNjsn00gMQTZZaHtzWkHUxY93TYCCojr
# QOUGMAu4Fkvc77xVCf/GPhIudrPczkLv+XZX4bcKBUCYWJpdcRaTcYxlgepv84n3
# +3OttOe/2Y5vqgtPJfO44dXddZhogfiqwNGAwsTEOYnB9smebNd0+dmX+E/CmgrN
# Xo/4GengpZ/E8JIh5i15Jcki+cPwOoRXrToW9GOUEB1d0MYwggVVMIIEPaADAgEC
# AhNiAAAABat2SURxouO1AAAAAAAFMA0GCSqGSIb3DQEBBQUAMEYxEzARBgoJkiaJ
# k/IsZAEZFgNzcGIxFjAUBgoJkiaJk/IsZAEZFgZtb3Jpb24xFzAVBgNVBAMTDm1v
# cmlvbi1WREMxLUNBMB4XDTE4MDMzMDExMDgyNVoXDTIwMDMyOTExMDgyNVowgYUx
# EzARBgoJkiaJk/IsZAEZFgNzcGIxFjAUBgoJkiaJk/IsZAEZFgZtb3Jpb24xFDAS
# BgNVBAsTC0RlcGFydG1lbnRzMRgwFgYDVQQLEw9PU0EgRGVwYXJ0YW1lbnQxJjAk
# BgNVBAMMHdCa0YPQt9C90LXRhtC+0LIg0KHQtdGA0LPQtdC5MIGfMA0GCSqGSIb3
# DQEBAQUAA4GNADCBiQKBgQDOZx8eOoePQDUTaHbhKvV1d+JNFM3oPEBPy6rT11HC
# zrQaQa3+jMIg70ONSdLpySRV0J/r2bVKtP3dOSgAYDNMH3JDcs/lrMXCns31CTNv
# 48h/BVgfhR6G/YLMJ8mqe6SwnCJKCCIHFEIUmUQsK6C/lVNKCSTK7F/4L3sNAHkd
# cQIDAQABo4ICfjCCAnowPQYJKwYBBAGCNxUHBDAwLgYmKwYBBAGCNxUIhq/VIo2B
# DoednR+GusMihuv8EIFehYGIEYO6wQUCAWQCAQIwEwYDVR0lBAwwCgYIKwYBBQUH
# AwMwCwYDVR0PBAQDAgeAMBsGCSsGAQQBgjcVCgQOMAwwCgYIKwYBBQUHAwMwHQYD
# VR0OBBYEFJ1B3ovAIsqKw4Ry27tEo3WEPsDvMB8GA1UdIwQYMBaAFEcNrIh5wIqS
# MPHHNN17u2ZTOkM8MIHIBgNVHR8EgcAwgb0wgbqggbeggbSGgbFsZGFwOi8vL0NO
# PW1vcmlvbi1WREMxLUNBLENOPVZEQzEsQ049Q0RQLENOPVB1YmxpYyUyMEtleSUy
# MFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9bW9yaW9u
# LERDPXNwYj9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xh
# c3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnQwgb8GCCsGAQUFBwEBBIGyMIGvMIGsBggr
# BgEFBQcwAoaBn2xkYXA6Ly8vQ049bW9yaW9uLVZEQzEtQ0EsQ049QUlBLENOPVB1
# YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRp
# b24sREM9bW9yaW9uLERDPXNwYj9jQUNlcnRpZmljYXRlP2Jhc2U/b2JqZWN0Q2xh
# c3M9Y2VydGlmaWNhdGlvbkF1dGhvcml0eTAtBgNVHREEJjAkoCIGCisGAQQBgjcU
# AgOgFAwSY29udHJvbEBtb3Jpb24uc3BiMA0GCSqGSIb3DQEBBQUAA4IBAQCUUjjH
# eetX9wMAt7WYGhBMeqiQnIeXUBUDxnFUYCnP3vhAJs3pmyEsCu3VPsbY7M+JWHFU
# SC8UpI6LHcA5CpTDXH6SRFgYBY5J/RaUItfymqahtRJLApi0zGaym1UNV6yxFxTq
# /JC+YVe+idj6zyt6w0282KJicOXce5nP3eJwRAjqXXEZ5XFr8FGIEN4VSrG+jF3P
# g0i3oBGcmO9ZDyGfEItLVTnSxsXIP/4/AbNHLyfBuyRTcGILuUt2FTjLynG0qSet
# cJRbdT5UD56jtBpw5Y9QlhGuPEWq5R5q0CuNQozj+w5eRTRb4CKmvBQ25tIXRtX6
# CET6MckiTHp8wPOZMYIDxDCCA8ACAQEwXTBGMRMwEQYKCZImiZPyLGQBGRYDc3Bi
# MRYwFAYKCZImiZPyLGQBGRYGbW9yaW9uMRcwFQYDVQQDEw5tb3Jpb24tVkRDMS1D
# QQITYgAAAAWrdklEcaLjtQAAAAAABTAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIB
# DDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEE
# AYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUUMV4XFdMD8cy
# fJCq0W+oH1f0ad0wDQYJKoZIhvcNAQEBBQAEgYAgG5JrtR8xpYB0Kfn5gfwHqvYj
# kLSc32Ja+q3q44eQFJYXEdeQrppAV7PSytrekUPP9XKAqlI4MT9vQXtn4eyLKVtd
# sFkVBZXbR4b5W3CB5lbBqEQVQyGSVpCUy0/HLWyWLqK+H+9lwzjXMoWDPNh1WF2W
# gh8Ncz2TijVrYi1xV6GCAkMwggI/BgkqhkiG9w0BCQYxggIwMIICLAIBATCBqTCB
# lTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAlVUMRcwFQYDVQQHEw5TYWx0IExha2Ug
# Q2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBOZXR3b3JrMSEwHwYDVQQLExho
# dHRwOi8vd3d3LnVzZXJ0cnVzdC5jb20xHTAbBgNVBAMTFFVUTi1VU0VSRmlyc3Qt
# T2JqZWN0Ag8WiPA5JV5jjmkUOQfmMwswCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJ
# AzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE5MDExODA4NTIxNFowIwYJ
# KoZIhvcNAQkEMRYEFFx+SDCbY9YDyuSIzspVOq9O1lHJMA0GCSqGSIb3DQEBAQUA
# BIIBANFlurkcPtQvoXCG1dZZ/3EkTopdWMBXIgPB+8KVRrqKl1yMdnBP3JjIJrPO
# TuDqKs5Bslwwk+p+XHh+lj32N3BMjzZ8dOIA9bjL0cH5DoPaVgg1J8/5msEkiImm
# +6QpcRYn0Fem26Ikay6niN2chPc0qwbex3HAf9MJ1KnqoSgTtoyVDsrArCvqn16Y
# awodBBNobBuXvPAkV5+wevf5W/r7RAwpod8mndzZKy2vFak1u4tLe8GOXr1iNaVS
# 9Jsv/0j1WIGGUvJDk2rO9KxTQqv91FI9blTg6qDJSHYp7FpMpdr98EPkWL9vpesL
# 9OdkCDr1m6bVEgiXAcjoE9UpA14=
# SIG # End signature block
