Set-ADUser -Identity P.Abrosimov -PasswordNeverExpires $true
Set-ADUser -Identity D.Avstriyskiy -PasswordNeverExpires $true
Set-ADUser -Identity I.Avtenyuk -PasswordNeverExpires $true
Set-ADUser -Identity A.Aleynikov -PasswordNeverExpires $true
Set-ADUser -Identity E.Antonov -PasswordNeverExpires $true
Set-ADUser -Identity E.Arnautova -PasswordNeverExpires $true
Set-ADUser -Identity L.Arhipova -PasswordNeverExpires $true
Set-ADUser -Identity D.Balay -PasswordNeverExpires $true
Set-ADUser -Identity B.Bapaev -PasswordNeverExpires $true
Set-ADUser -Identity A.Basov -PasswordNeverExpires $true
Set-ADUser -Identity K.Bystrov -PasswordNeverExpires $true
Set-ADUser -Identity M.Vaynshteyn -PasswordNeverExpires $true
Set-ADUser -Identity D.Vasilev -PasswordNeverExpires $true
Set-ADUser -Identity D.Vasilev -PasswordNeverExpires $true
Set-ADUser -Identity I.Vasileva -PasswordNeverExpires $true
Set-ADUser -Identity I.Vladimirovich -PasswordNeverExpires $true
Set-ADUser -Identity Yu.Vodopyanova -PasswordNeverExpires $true
Set-ADUser -Identity N.Garshin -PasswordNeverExpires $true
Set-ADUser -Identity L.Girova -PasswordNeverExpires $true
Set-ADUser -Identity M.Giria -PasswordNeverExpires $true
Set-ADUser -Identity E.Glaznikova -PasswordNeverExpires $true
Set-ADUser -Identity I.Golovina -PasswordNeverExpires $true
Set-ADUser -Identity T.Grischuk -PasswordNeverExpires $true
Set-ADUser -Identity E.Gurkova -PasswordNeverExpires $true
Set-ADUser -Identity O.Demchuk -PasswordNeverExpires $true
Set-ADUser -Identity M.Derbichev -PasswordNeverExpires $true
Set-ADUser -Identity M.Deshevaya -PasswordNeverExpires $true
Set-ADUser -Identity S.Dopira -PasswordNeverExpires $true
Set-ADUser -Identity K.Drugov -PasswordNeverExpires $true
Set-ADUser -Identity E.Dudarev -PasswordNeverExpires $true
Set-ADUser -Identity D.Dudenkova -PasswordNeverExpires $true
Set-ADUser -Identity A.Dudnik -PasswordNeverExpires $true
Set-ADUser -Identity I.Duhovskiy -PasswordNeverExpires $true
Set-ADUser -Identity S.Evdokimov -PasswordNeverExpires $true
Set-ADUser -Identity P.Epifanova -PasswordNeverExpires $true
Set-ADUser -Identity E.Zhigalova -PasswordNeverExpires $true
Set-ADUser -Identity D.ZHigulskii -PasswordNeverExpires $true
Set-ADUser -Identity E.Zaitceva -PasswordNeverExpires $true
Set-ADUser -Identity V.Shumilova -PasswordNeverExpires $true
Set-ADUser -Identity E.Ischenko -PasswordNeverExpires $true
Set-ADUser -Identity V.Karabuta -PasswordNeverExpires $true
Set-ADUser -Identity V.Karpova -PasswordNeverExpires $true
Set-ADUser -Identity Yu.Kirichenko -PasswordNeverExpires $true
Set-ADUser -Identity E.Kovalev -PasswordNeverExpires $true
Set-ADUser -Identity A.Konovalov -PasswordNeverExpires $true
Set-ADUser -Identity A.Kononova -PasswordNeverExpires $true
Set-ADUser -Identity A.Korepina -PasswordNeverExpires $true
Set-ADUser -Identity A.Kuznetsova -PasswordNeverExpires $true
Set-ADUser -Identity A.Levitskiy -PasswordNeverExpires $true
Set-ADUser -Identity I.Leontiev -PasswordNeverExpires $true
Set-ADUser -Identity A.Linnik -PasswordNeverExpires $true
Set-ADUser -Identity R.Lipatov -PasswordNeverExpires $true
Set-ADUser -Identity G.Loginov -PasswordNeverExpires $true
Set-ADUser -Identity D.Lomov -PasswordNeverExpires $true
Set-ADUser -Identity D.Lyubanskiy -PasswordNeverExpires $true
Set-ADUser -Identity I.Mazaleckaya -PasswordNeverExpires $true
Set-ADUser -Identity D.Makarchuk -PasswordNeverExpires $true
Set-ADUser -Identity A.Mamontov -PasswordNeverExpires $true
Set-ADUser -Identity M.Manistov -PasswordNeverExpires $true
Set-ADUser -Identity D.Maratkanov -PasswordNeverExpires $true
Set-ADUser -Identity E.Martynovich -PasswordNeverExpires $true
Set-ADUser -Identity M.Marchenko -PasswordNeverExpires $true
Set-ADUser -Identity M.Matveev -PasswordNeverExpires $true
Set-ADUser -Identity N.Mihailovich -PasswordNeverExpires $true
Set-ADUser -Identity K.Nesterova -PasswordNeverExpires $true
Set-ADUser -Identity N.Onipko -PasswordNeverExpires $true
Set-ADUser -Identity N.Oskolskaya -PasswordNeverExpires $true
Set-ADUser -Identity A.Padalko -PasswordNeverExpires $true
Set-ADUser -Identity A.Patraeva -PasswordNeverExpires $true
Set-ADUser -Identity M.Patrakhina -PasswordNeverExpires $true
Set-ADUser -Identity V.Petelin -PasswordNeverExpires $true
Set-ADUser -Identity D.Pilipenko -PasswordNeverExpires $true
Set-ADUser -Identity O.Pleshchenkova -PasswordNeverExpires $true
Set-ADUser -Identity M.Pogodina -PasswordNeverExpires $true
Set-ADUser -Identity M.Ponyatov -PasswordNeverExpires $true
Set-ADUser -Identity A.Popov -PasswordNeverExpires $true
Set-ADUser -Identity V.Prasol -PasswordNeverExpires $true
Set-ADUser -Identity D.Pryahina -PasswordNeverExpires $true
Set-ADUser -Identity S.Pushkin -PasswordNeverExpires $true
Set-ADUser -Identity T.Romanenko -PasswordNeverExpires $true
Set-ADUser -Identity E.Romanova -PasswordNeverExpires $true
Set-ADUser -Identity N.Samoylov -PasswordNeverExpires $true
Set-ADUser -Identity A.Semenova -PasswordNeverExpires $true
Set-ADUser -Identity N.Sendik -PasswordNeverExpires $true
Set-ADUser -Identity A.Sinilo -PasswordNeverExpires $true
Set-ADUser -Identity A.Skorikov -PasswordNeverExpires $true
Set-ADUser -Identity A.Smirnova -PasswordNeverExpires $true
Set-ADUser -Identity O.Smuglina -PasswordNeverExpires $true
Set-ADUser -Identity V.Sologub -PasswordNeverExpires $true
Set-ADUser -Identity A.Surmin -PasswordNeverExpires $true
Set-ADUser -Identity V.Sukharev -PasswordNeverExpires $true
Set-ADUser -Identity K.Tihomirov -PasswordNeverExpires $true
Set-ADUser -Identity E.Trofimova -PasswordNeverExpires $true
Set-ADUser -Identity O.Turkin -PasswordNeverExpires $true
Set-ADUser -Identity A.Uspenskaya -PasswordNeverExpires $true
Set-ADUser -Identity D.Fedotov -PasswordNeverExpires $true
Set-ADUser -Identity D.Fedotov -PasswordNeverExpires $true
Set-ADUser -Identity A.Furin -PasswordNeverExpires $true
Set-ADUser -Identity A.Han -PasswordNeverExpires $true
Set-ADUser -Identity V.Chemeris -PasswordNeverExpires $true
Set-ADUser -Identity A.chernyaev -PasswordNeverExpires $true
Set-ADUser -Identity A.Chugunov -PasswordNeverExpires $true
Set-ADUser -Identity N.SHaronova -PasswordNeverExpires $true
Set-ADUser -Identity I.SHemiakina -PasswordNeverExpires $true
Set-ADUser -Identity E.Shkolnik -PasswordNeverExpires $true
Set-ADUser -Identity E.Shkutova -PasswordNeverExpires $true
